name: ci-pydgraph-check-protos

on:
  push:
    branches:
      - any

permissions:
  contents: read

jobs:
  pydgraph-build:
    runs-on: warp-ubuntu-latest-x64-16x
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ github.event.inputs.releasetag }}"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev]
          # use twine to upload to pypi
          python -m pip install twine
      - name: Verify that protobufs are checked in
        run: |
          python scripts/protogen.py
          git diff --exit-code -- .
